"""Disease spin-up: advance the uncontrolled epizootic to an observed prevalence.

Why this exists
---------------
``susceptible_spinup.py`` fixes the *demographic* initial condition. This module
fixes the *epidemiological* one, and it exists because the horizon and the
calibration otherwise describe different problems.

The initial condition in ``initial_conditions.infected_gaussians`` is an
introduction: each focus integrates to one index animal. That is the right
object if the question is "what happens when CWD arrives". But the planning
horizon is twenty years, which is a management horizon, and the management
question is posed of a herd that already has the disease. At a calibrated R0 an
introduction takes decades to become visible, so a control problem started from
one animal hands the optimizer a trajectory with almost nothing on it: the
fast-decaying modes of the linearisation run out before the slowly growing one
emerges, and prevalence falls for the first part of the run.

The fix is to separate the two. Run the uncontrolled system forward from the
index case until domain-wide prevalence reaches an observed level, and use that
state -- all four compartments -- as t = 0 for the control problem. The clock
starts on an established epizootic, which is the thing a cull is actually
applied to.

Two properties make this better than seeding a prevalence field by hand. The
front is generated by the model rather than assumed, so it is consistent with
the mesh, the land cover and the diffusion tensor rather than being an
independent guess laid on top of them. And the initial condition becomes
derived rather than invented: the only free choice is the target prevalence,
which is an observable.

Cost and caching
----------------
The spin-up can be long -- at low R0 it is centuries of simulated time -- but it
is *precomputation*, not part of the optimisation, and it is paid once. As with
the susceptible field it is cached beside the mesh bundle, keyed by a signature
of everything the answer depends on: the mesh, the land-cover arrays, the
disease-free field it starts from, every reaction parameter, the diffusion
tensor, the foci, and the target prevalence. Change any of them and the cache is
recomputed rather than silently reused.

The control is identically zero throughout. This is the do-nothing trajectory,
so the same cached state is the correct starting point for the uncontrolled
solver and for the control driver, and the two remain directly comparable.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np
from mpi4py import MPI

# Cached artefacts live in the mesh bundle folder for the same reason the
# susceptible equilibrium does: one per mesh + land cover + parameter set,
# shared by every run on that bundle.
DISEASE_ARRAY_NAME = "disease_initial_state.npy"
DISEASE_SIGNATURE_NAME = "disease_initial_state.json"


def default_disease_paths(mesh_path):
    """Where the cached state and its signature live for a given mesh."""
    folder = Path(mesh_path).expanduser().resolve().parent
    return folder / DISEASE_ARRAY_NAME, folder / DISEASE_SIGNATURE_NAME


def _digest(array):
    contiguous = np.ascontiguousarray(np.asarray(array, dtype=np.float64))
    return hashlib.sha256(contiguous.tobytes()).hexdigest()[:16]


def spinup_time_step(parameters):
    """Spin-up step, defaulting to the main simulation's step when unset."""
    configured = parameters["disease_spinup"]["time_step_years"]
    if configured is None:
        return float(parameters["time"]["time_step_years"])
    return float(configured)


def disease_signature(domain, carrying_capacity, diffusivity,
                      susceptible_equilibrium, parameters):
    """The inputs the spun-up state actually depends on.

    Broader than the susceptible signature, because this solve involves the
    whole reaction system rather than the S block alone: every reaction rate is
    included, along with the foci that seed it and the prevalence it stops at.
    """
    tensor = parameters["diffusion_tensor"]
    reaction = parameters["reaction"]
    spinup = parameters["disease_spinup"]
    scales = tensor["compartment_scales"]
    foci = parameters["initial_conditions"]["infected_gaussians"]
    return {
        "geometry_digest": _digest(domain.geometry.x),
        "carrying_capacity_digest": _digest(carrying_capacity),
        "diffusivity_digest": _digest(diffusivity),
        "susceptible_equilibrium_digest": _digest(susceptible_equilibrium),
        "node_count": int(np.asarray(carrying_capacity).size),
        "reaction": {key: float(value) for key, value in reaction.items()
                     if key != "_notes"},
        "kappa": float(tensor["kappa"]),
        "isotropy": float(tensor["isotropy"]),
        "activation_steepness": float(tensor["activation_steepness"]),
        "activation_cosine_threshold": float(
            tensor["activation_cosine_threshold"]
        ),
        "compartment_scales": {key: float(value)
                               for key, value in scales.items()},
        "carrying_capacity_base": float(
            parameters["land_cover"]["carrying_capacity_base"]
        ),
        "infected_gaussians": [
            {
                "center": [float(value) for value in focus["center"]],
                "mean": float(focus["mean"]),
                "standard_deviation": float(focus["standard_deviation"]),
            }
            for focus in foci
        ],
        "target_prevalence": float(spinup["target_prevalence"]),
        "time_step_years": float(spinup_time_step(parameters)),
    }


def _print(comm, message):
    if comm.rank == 0:
        print(message)


def _progress(comm, years, max_years, prevalence, target, width=40):
    if comm.rank != 0:
        return
    # Progress is reported against prevalence rather than against elapsed time,
    # because prevalence is the stopping criterion and the run length is not
    # known in advance. It grows roughly exponentially, so the bar is driven by
    # log prevalence to keep it from sitting at zero for most of the solve.
    if prevalence <= 0.0:
        fraction = 0.0
    else:
        fraction = min(1.0, np.log(prevalence / 1e-6) / np.log(target / 1e-6))
    filled = min(width, int(width * max(0.0, fraction)))
    bar = "=" * filled + "-" * (width - filled)
    sys.stdout.write(
        f"\rDisease spin-up:     [{bar}] prevalence {prevalence:8.4%} "
        f"of {target:.2%} target   t = {years:7.1f} yr"
    )
    sys.stdout.flush()


def run_disease_spinup(advance, prevalence, read_state, parameters,
                       comm=MPI.COMM_WORLD, verbose=True):
    """Advance the uncontrolled system until prevalence reaches the target.

    The caller supplies the stepping machinery, so this works unchanged for the
    control driver and the uncontrolled solver:

      advance()    -- advance the state one time step, in place, with v = 0
      prevalence() -- domain-wide (I + R) / (S + I + R), collective
      read_state() -- the current mixed nodal array, as a copy

    Returns ``(values, info)``.
    """
    spinup = parameters["disease_spinup"]
    target = float(spinup["target_prevalence"])
    dt = spinup_time_step(parameters)
    max_years = float(spinup["max_duration_years"])
    total_steps = max(1, int(round(max_years / dt)))

    start = prevalence()
    if verbose:
        _print(
            comm,
            f"Disease spin-up: advancing the uncontrolled system to "
            f"{target:.2%} prevalence, from {start:.4%}, up to {max_years:g} yr "
            f"({total_steps} steps of {dt:g} yr).",
        )
    if start >= target:
        # Nothing to do: the foci already exceed the target. Left as a normal
        # exit rather than an error, so that raising the focus amplitude and
        # lowering the target both remain usable ways to skip the spin-up.
        if verbose:
            _print(comm, "  Initial prevalence already at or above target.")
        return read_state(), {
            "converged": True, "years_run": 0.0, "steps_run": 0,
            "initial_prevalence": float(start),
            "final_prevalence": float(start),
            "target_prevalence": float(target),
        }

    reached = False
    current = start
    completed = 0
    for step in range(total_steps):
        advance()
        completed = step + 1
        current = prevalence()
        if verbose and completed % 200 == 0:
            _progress(comm, completed * dt, max_years, current, target)
        if current >= target:
            reached = True
            break

    if verbose:
        _progress(comm, completed * dt, max_years, current, target)
        if comm.rank == 0:
            print()
        if reached:
            _print(
                comm,
                f"Disease spin-up reached {current:.3%} prevalence after "
                f"{completed * dt:g} yr.",
            )
        else:
            _print(
                comm,
                f"WARNING: disease spin-up hit its {max_years:g} yr cap at "
                f"{current:.3%} prevalence, short of the {target:.2%} target. "
                "The saved state is not the intended initial condition; raise "
                "disease_spinup.max_duration_years, lower the target, or check "
                "that R0 exceeds one for these parameters.",
            )

    info = {
        "converged": bool(reached),
        "years_run": float(completed * dt),
        "steps_run": int(completed),
        "initial_prevalence": float(start),
        "final_prevalence": float(current),
        "target_prevalence": float(target),
    }
    return read_state(), info


def _cache_mismatch(stored, expected):
    """Names of the signature entries that disagree, if any."""
    if not isinstance(stored, dict):
        return ["<unreadable signature>"]
    changed = []
    for key, value in expected.items():
        if key not in stored:
            changed.append(key)
        elif isinstance(value, float):
            if not np.isclose(float(stored[key]), value, rtol=1e-12, atol=0.0):
                changed.append(key)
        elif stored[key] != value:
            changed.append(key)
    return changed


def disease_initial_state(expected, expected_size, compute,
                          array_path, signature_path,
                          comm=MPI.COMM_WORLD, recompute=False, verbose=True):
    """The initial mixed state: the cached spun-up epizootic, or a fresh one.

    ``compute()`` runs the spin-up and returns ``(values, info)``; it is only
    called when the cache is absent or stale. ``expected`` is the signature from
    :func:`disease_signature`.
    """
    array_path = Path(array_path)
    signature_path = Path(signature_path)

    reason = None
    if recompute:
        reason = "recompute requested"
    elif not array_path.is_file():
        reason = f"no cached state at {array_path}"
    elif not signature_path.is_file():
        reason = f"cached state has no signature file at {signature_path}"
    else:
        try:
            with signature_path.open("r", encoding="utf-8") as stream:
                stored = json.load(stream)
        except (OSError, json.JSONDecodeError):
            stored = None
        changed = _cache_mismatch((stored or {}).get("inputs"), expected)
        if changed:
            reason = "cached state is stale (changed: " + ", ".join(changed) + ")"
        else:
            values = np.load(array_path)
            if values.size != expected_size:
                reason = (
                    f"cached state has {values.size} values but this mesh and "
                    f"function space expect {expected_size}"
                )
            else:
                _print(comm, f"Disease initial condition: {array_path}")
                result = stored.get("result") or {}
                if result:
                    _print(
                        comm,
                        f"  (spun up {float(result.get('years_run', float('nan'))):g} yr "
                        f"to {float(result.get('final_prevalence', float('nan'))):.3%} "
                        "prevalence)",
                    )
                    if not result.get("converged", True):
                        _print(
                            comm,
                            "  WARNING: that run did not reach its target "
                            "prevalence.",
                        )
                return values

    _print(comm, f"Computing disease initial state: {reason}.")
    values, info = compute()

    # Nodal arrays are indexed by local DOF, so a cache written under one
    # partition is meaningless under another -- the same reason the susceptible
    # equilibrium is a serial artefact. Recompute rather than write a file that
    # would be silently wrong.
    if comm.size > 1:
        _print(
            comm,
            "Running on more than one rank, so the spun-up state is not cached "
            "(nodal arrays are partition-dependent). Run once in serial to "
            "write the cache.",
        )
        return values

    np.save(array_path, values)
    with signature_path.open("w", encoding="utf-8") as stream:
        json.dump({"inputs": expected, "result": info}, stream, indent=2)
    _print(comm, f"Saved disease initial state to {array_path}")
    return values
